name: Deploy Firebase Functions

on:
  push:
    branches:
      - main # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: echo "$FIREBASE_SERVICE_ACCOUNT" > serviceAccountKey.json

      - name: Deploy to Firebase
        run: firebase deploy --only functions --token "$FIREBASE_TOKEN"
